travis:
  secure:
    BINSTAR_TOKEN: Lck9xMAeSKcnWFfuI6Yc1ewfgm22roPwyhn9HZ8sFo75P/K+FIG1SVW7J9D9ujgzwd3whHtK1XJXXMua7jE6DEt1//b18voRoQ02/1bvVu0fsGu3nV6TrvGRr3/o6ciZIaxFLAydix67mWobO3HshebZKoz0pGG+Wcq5+4key1C8ss9CSm9I48lyyFe7+wJELvIff7re5HbwVLP2IXy/1p4JMjtHqkGPCuKROAbFW5SoFoKx6Chfpcib+fINsGCzOIFDvDx8JnmhnOmvu9eWb82YfFo6KD/pEm1PWd+3SwzGYfF6b895gx8Zmv5Mr01LMJ7sNRDHrzIuDfzFXQLUCGrEiqhZknzC8Wxc+t6Hm+M/MNLKWuTum9i5A+hADNebEPfH3gJIV54auMy2qjVcWMkLWC1ZdMitbMuyTK/hWrPMSkrogZs91Cfu0RmHqNt3zxSFDS5hWuZ36gtOcJxU+sdm4Xz7D/2AoSx09VNP6YjWP7Mz9MmNd1yqBTA2iZHKcZ2LM4utwQBoaoP7WkgpUAHCGH9joKDGUBrKx7BVBWzip+urvN7TLwmqcEBzW+OFFNqeT8GeQNKu8GmkcKU3KzICYZ3M0ELmF5Sh43LXgZP9s3B5iFRiP4aiECTiSBJjo30q2AAhCgeEs1hvELg/wcAFmdvVxsMepmlFwlggg+g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
